apiVersion: v2
name: lz-kong
description: A Helm chart for Kong

# Installs Kong OSS (open-source) which is what we install at Legalzoom. 
# Legalzoom's Kong install is same as public, but it adds a custom plugin using their Golang PDK to manage authentication.

# See this Kong install guide: https://docs.konghq.com/kubernetes-ingress-controller/latest/get-started/

# This chart installs the Kong CRDs, a Kong GatewayClass, and Kong ingress Helm chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: ingress
  version: ">= 0.10.1"
  repository: "https://charts.konghq.com"
